import Component from '@glimmer/component';
import type { BasicDropdownDefaultBlock } from 'ember-basic-dropdown/components/basic-dropdown';
import type { Dropdown, TRootEventType } from 'ember-basic-dropdown/types';
import type Owner from '@ember/owner';
import type { CalculatePosition, HorizontalPosition, VerticalPosition } from 'ember-basic-dropdown/utils/calculate-position';
import type { ComponentLike } from '@glint/template';
import type { PowerSelectPlaceholderSignature } from './power-select/placeholder';
import type { PowerSelectSearchMessageSignature } from './power-select/search-message';
import type { PowerSelectNoMatchesMessageSignature } from './power-select/no-matches-message';
import type { BasicDropdownTriggerSignature } from 'ember-basic-dropdown/components/basic-dropdown-trigger';
import type { BasicDropdownContentSignature } from 'ember-basic-dropdown/components/basic-dropdown-content';
import type { PowerSelectLabelSignature } from './power-select/label';
import type { PowerSelectTriggerSignature } from './power-select/trigger';
import type { PowerSelectBeforeOptionsSignature } from './power-select/before-options';
import type { PowerSelectOptionsSignature } from './power-select/options';
import type { PowerSelectPowerSelectGroupSignature } from './power-select/power-select-group';
import type { DefaultHighlightedParams, MatcherFn, Option, PowerSelectAfterOptionsSignature, PowerSelectSelectedItemSignature, Select, Selected, TLabelClickAction, TSearchFieldPosition } from '../types.ts';
export interface PowerSelectArgs<T, IsMultiple extends boolean = false, TExtra = unknown> {
    highlightOnHover?: boolean;
    placeholderComponent?: ComponentLike<PowerSelectPlaceholderSignature<T, TExtra, IsMultiple>>;
    searchMessage?: string;
    searchMessageComponent?: ComponentLike<PowerSelectSearchMessageSignature<T, TExtra, IsMultiple>>;
    noMatchesMessage?: string;
    noMatchesMessageComponent?: ComponentLike<PowerSelectNoMatchesMessageSignature<T, TExtra, IsMultiple>>;
    matchTriggerWidth?: boolean;
    resultCountMessage?: (resultCount: number) => string;
    options?: readonly T[] | Promise<readonly T[]>;
    selected?: Selected<T, IsMultiple> | Promise<Selected<T, IsMultiple>>;
    multiple?: IsMultiple;
    destination?: string;
    destinationElement?: HTMLElement;
    closeOnSelect?: boolean;
    renderInPlace?: boolean;
    preventScroll?: boolean;
    defaultHighlighted?: ((params: DefaultHighlightedParams<T>) => Option<T> | undefined) | Option<T> | undefined;
    searchField?: string;
    labelClass?: string;
    labelText?: string;
    labelTag?: keyof HTMLElementTagNameMap;
    labelClickAction?: TLabelClickAction;
    ariaLabel?: string;
    ariaLabelledBy?: string;
    loadingMessage?: string;
    placeholder?: string;
    dropdownClass?: string;
    allowClear?: boolean;
    searchEnabled?: boolean;
    animationEnabled?: boolean;
    tabindex?: number | string;
    searchPlaceholder?: string;
    searchFieldPosition?: TSearchFieldPosition;
    verticalPosition?: VerticalPosition;
    horizontalPosition?: HorizontalPosition;
    triggerId?: string;
    disabled?: boolean;
    title?: string;
    triggerRole?: string;
    required?: string;
    triggerClass?: string;
    ariaInvalid?: string;
    eventType?: BasicDropdownTriggerSignature['Args']['eventType'];
    rootEventType?: TRootEventType;
    ariaDescribedBy?: string;
    calculatePosition?: CalculatePosition;
    ebdTriggerComponent?: ComponentLike<BasicDropdownTriggerSignature>;
    ebdContentComponent?: ComponentLike<BasicDropdownContentSignature>;
    labelComponent?: ComponentLike<PowerSelectLabelSignature<T, TExtra, IsMultiple>>;
    triggerComponent?: ComponentLike<PowerSelectTriggerSignature<T, TExtra, IsMultiple>>;
    selectedItemComponent?: ComponentLike<PowerSelectSelectedItemSignature<T, TExtra, IsMultiple>>;
    beforeOptionsComponent?: ComponentLike<PowerSelectBeforeOptionsSignature<T, TExtra, IsMultiple>>;
    optionsComponent?: ComponentLike<PowerSelectOptionsSignature<T, TExtra, IsMultiple>>;
    groupComponent?: ComponentLike<PowerSelectPowerSelectGroupSignature<T, TExtra, IsMultiple>>;
    afterOptionsComponent?: ComponentLike<PowerSelectAfterOptionsSignature<T, TExtra, IsMultiple>>;
    extra?: TExtra;
    matcher?: MatcherFn<T>;
    initiallyOpened?: boolean;
    typeAheadOptionMatcher?: MatcherFn<T>;
    buildSelection?: (selected: Option<T>, select: Select<T, IsMultiple>) => Selected<T, IsMultiple>;
    onChange: (selection: Selected<T, IsMultiple>, select: Select<T, IsMultiple>, event?: Event) => void;
    search?: (term: string, select: Select<T, IsMultiple>) => readonly T[] | Promise<readonly T[]>;
    onOpen?: (select: Select<T, IsMultiple>, e: Event | undefined) => boolean | void | undefined;
    onClose?: (select: Select<T, IsMultiple>, e: Event | undefined) => boolean | void | undefined;
    onInput?: (term: string, select: Select<T, IsMultiple>, e: Event) => string | boolean | void;
    onKeydown?: (select: Select<T, IsMultiple>, e: KeyboardEvent) => boolean | void | undefined;
    onFocus?: (select: Select<T, IsMultiple>, event: FocusEvent) => void;
    onBlur?: (select: Select<T, IsMultiple>, event: FocusEvent) => void;
    scrollTo?: (option: Selected<T>, select: Select<T, IsMultiple>) => void;
    registerAPI?: (select: Select<T, IsMultiple>) => void;
}
export interface PowerSelectSignature<T, IsMultiple extends boolean = false, TExtra = undefined> {
    Element: Element;
    Args: PowerSelectArgs<T, IsMultiple, TExtra>;
    Blocks: {
        default: [option: Option<T>, select: Select<T, IsMultiple>];
    };
}
export default class PowerSelectComponent<T, IsMultiple extends boolean = false, TExtra = undefined> extends Component<PowerSelectSignature<T, IsMultiple, TExtra>> {
    _publicAPIActions: {
        search: (term: string) => void;
        highlight: (opt: Option<T> | undefined) => void;
        select: (selected: Selected<T, IsMultiple>, e?: Event) => void;
        choose: (selected: Option<T>, e?: Event) => void;
        scrollTo: (option: Selected<T>) => void;
        labelClick: (event: MouseEvent) => true | undefined;
    };
    private _resolvedOptions?;
    private _resolvedSelected?;
    private _repeatingChar;
    private _expirableSearchText;
    private _searchResult?;
    isActive: boolean;
    loading: boolean;
    searchText: string;
    lastSearchedText: string;
    highlighted?: Option<T> | undefined;
    storedAPI: Select<T, IsMultiple>;
    private _uid;
    private _lastOptionsPromise?;
    private _lastSelectedPromise?;
    private _lastSearchPromise?;
    private _filterResultsCache;
    constructor(owner: Owner, args: PowerSelectArgs<T, IsMultiple, TExtra>);
    willDestroy(): void;
    get highlightOnHover(): boolean;
    get labelClickAction(): TLabelClickAction;
    get highlightedIndex(): string;
    get searchMessage(): string;
    get noMatchesMessage(): string;
    get resultCountMessage(): string;
    get matchTriggerWidth(): boolean;
    get mustShowSearchMessage(): boolean;
    get mustShowNoMessages(): boolean;
    get results(): T[];
    get options(): T[];
    get resultsCount(): number;
    get selected(): Selected<T, IsMultiple> | undefined;
    get ariaMultiSelectable(): boolean;
    get triggerId(): string;
    get labelId(): string;
    get ariaLabelledBy(): string | undefined;
    get searchFieldPosition(): TSearchFieldPosition;
    get tabindex(): string | number;
    get buildSelection(): PowerSelectArgs<T, IsMultiple, TExtra>['buildSelection'];
    get labelComponent(): ComponentLike<PowerSelectLabelSignature<T, TExtra, IsMultiple>>;
    get triggerComponent(): ComponentLike<PowerSelectTriggerSignature<T, TExtra, IsMultiple>>;
    get placeholderComponent(): ComponentLike<PowerSelectPlaceholderSignature<T, TExtra, IsMultiple>>;
    get beforeOptionsComponent(): ComponentLike<PowerSelectBeforeOptionsSignature<T, TExtra, IsMultiple>>;
    get searchMessageComponent(): ComponentLike<PowerSelectSearchMessageSignature<T, TExtra, IsMultiple>>;
    get noMatchesMessageComponent(): ComponentLike<PowerSelectNoMatchesMessageSignature<T, TExtra, IsMultiple>>;
    get optionsComponent(): ComponentLike<PowerSelectOptionsSignature<T, TExtra, IsMultiple>>;
    get groupComponent(): ComponentLike<PowerSelectPowerSelectGroupSignature<T, TExtra, IsMultiple>>;
    handleOpen(_select: Dropdown, e: Event | undefined): boolean | void;
    handleClose(_select: Dropdown, e: Event | undefined): boolean | void;
    handleInput(e: InputEvent): void;
    handleKeydown(e: KeyboardEvent): boolean | void;
    handleTriggerKeydown(e: KeyboardEvent): boolean | void;
    _labelClick(event: MouseEvent): true | undefined;
    handleFocus(event: FocusEvent): void;
    handleBlur(event: FocusEvent): void;
    _search(term: string): void;
    _updateHighlighted(): void;
    _highlight(opt: Option<T> | undefined): void;
    _select(selected: Selected<T, IsMultiple>, e?: Event): void;
    _choose(selected: Option<T>, e?: Event): void;
    _scrollTo(option: Selected<T>): void;
    updateOptions: import("ember-modifier").FunctionBasedModifier<{
        Args: {
            Positional: unknown[];
            Named: import("ember-modifier/-private/signature").EmptyObject;
        };
        Element: Element;
    }>;
    updateSelected: import("ember-modifier").FunctionBasedModifier<{
        Args: {
            Positional: unknown[];
            Named: import("ember-modifier/-private/signature").EmptyObject;
        };
        Element: Element;
    }>;
    updateRegisterAPI: import("ember-modifier").FunctionBasedModifier<{
        Args: {
            Positional: [Select<T, IsMultiple>];
            Named: import("ember-modifier/-private/signature").EmptyObject;
        };
        Element: Element;
    }>;
    updatePerformSearch: import("ember-modifier").FunctionBasedModifier<{
        Args: {
            Positional: [string];
            Named: import("ember-modifier/-private/signature").EmptyObject;
        };
        Element: Element;
    }>;
    private __updateOptions;
    private __updateSelected;
    private __registerAPI;
    private __performSearch;
    private _defaultMultipleBuildSelection;
    focusInput(select: Select<T, IsMultiple>): void;
    _routeKeydown(select: Select<T, IsMultiple>, e: KeyboardEvent): boolean | void;
    _handleKeyTab(select: Select<T, IsMultiple>, e: KeyboardEvent): void;
    _handleKeyESC(select: Select<T, IsMultiple>, e: KeyboardEvent): void;
    _handleKeyEnter(select: Select<T, IsMultiple>, e: KeyboardEvent): boolean | void;
    _handleKeySpace(select: Select<T, IsMultiple>, e: KeyboardEvent): void;
    _handleKeyUpDown(select: Select<T, IsMultiple>, e: KeyboardEvent): void;
    _resetHighlighted(): void;
    _filter(options: T[], term: string, skipDisabled?: boolean): T[];
    _updateIsActive(value: boolean): void;
    findWithOffset(options: readonly T[], term: string, offset: number, skipDisabled?: boolean): Option<T> | undefined;
    publicAPI: (dropdown: BasicDropdownDefaultBlock) => Select<T, IsMultiple>;
    triggerTypingTask: import("ember-concurrency").TaskForAsyncTaskFunction<{
        restartable: boolean;
    }, (e: KeyboardEvent) => Promise<void>>;
}
//# sourceMappingURL=power-select.d.ts.map